[build]
  command = "npm run build"
  publish = ".next"

# Sitemap harus served as XML
[[headers]]
for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"

# Robots harus served as plain text
[[headers]]
for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"

# Next.js static assets cache
[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Redirects untuk image optimizer
[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"
